### ISSUE TITLE
Problem with SceneCreator when compiling in debug

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#463]
The new SceneCreator implementation requires to load plugins to work. 
To do that it calls the PluginManager...the problem is that in debug...the plugins have are not found.

https://ci.inria.fr/sofa-ci/job/ubuntu_clang-3.8_options-debug/436/testReport/

Is this because of the _d suffix ? 

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Yes and this is fixed by the InSimo PR.

**Comment by guparan** [comment]
Actually this is not fixed. See https://ci.inria.fr/sofa-ci/job/ubuntu_clang-3.8_options-debug/520/testReport/

**Comment by damienmarchal** [comment]
Probably because:
[ERROR][PluginManager] Plugin not found: "SceneCreator_d"

**Comment by fjourdes** [comment]
Regarding this "_d" stuff 
- apparently it is possible to set it globally ( see https://cmake.org/cmake/help/v3.4/variable/CMAKE_CONFIG_POSTFIX.html#variable:CMAKE_%3CCONFIG%3E_POSTFIX and https://cmake.org/cmake/help/v3.4/variable/CMAKE_DEBUG_POSTFIX.html ) even though apparently it does not work for executables ( see https://stackoverflow.com/questions/28893450/how-to-get-debug-postfix-in-executable-name) Anyway, this decision should be carefully made, even though my first thought would be that it would be better compared to approches like the one taken with sofa_add_plugin macro. See https://github.com/sofa-framework/sofa/issues/490
- The value of this variable could be used as the default one to set the SOFA_LIBSUFFIX value in the SofaHelper CMakeLists.txt
- @guparan  have you taken a look at the suggestion I made regarding PR #502 ? https://github.com/sofa-framework/sofa/pull/502#issuecomment-340518769

**Comment by damienmarchal** [comment]
@guparan & @fjourdes 
Can someone be in charge of solving this ?

**Comment by guparan** [comment]
@fjourdes 
- The SOFA_LIBSUFFIX variable is only used by PluginManager to find a lib. The problem here is that we are in a debug build and some libs like SceneCreator are not suffixed with "_d". I don't see where SOFA_LIBSUFFIX would be helpful.
- Not yet for #502. Will do asap...

@damienmarchal 
I'm on it. Quick and easy fix is to add `set_target_properties(${PROJECT_NAME} PROPERTIES DEBUG_POSTFIX "_d")` in SceneCreator's CMakeLists.

**Comment by guparan** [comment]
@fjourdes Just read #490 and indeed I bumped on the same design issue while resolving SceneCreator's problem. So, do you think it is better to add `set_target_properties(${PROJECT_NAME} PROPERTIES DEBUG_POSTFIX "_d")` in the lib's CMakeLists (like I did, PR to come)?

**Comment by fjourdes** [comment]
- Regarding your first comment: 
The second point had indeed nothing to do with the actual issue. I was just mentionning that it may be beneficial to use CMAKE_DEBUG_POSTFIX as the default value - provided it is not an empty string - for SOFA_LIBSUFFIX in terms of portability, "_d" being the fallback default value if CMAKE_DEBUG_POSTFIX is empty.
On the main CMakeLists.txt, CMAKE_DEBUG_POSTFIX could be set with "_d" as the default value.

- Regarding the second comment: 
 Right now setting the `DEBUG_POSTFIX` at the target level is the consistent way to do it with respect to how things are done in the current implementation.

- Finally right now I **don't** know what is the best way to do it, I guess some experiments could be made by just setting the `CMAKE_DEBUG_POSTFIX` at the main CMakeLists.txt level, keeping in mind the probable problem with executables mentioned in https://stackoverflow.com/questions/28893450/how-to-get-debug-postfix-in-executable-name. Maybe it has been fixed / changed in recent versions of CMake, however portability must remain a strong concern here. 
Ultimately whatever the best option is, it is **important** that these sort of decisions are **well documented**, including potential side effects.

**Comment by guparan** [comment]
Ok so we could get rid of a lot of `DEBUG_POSTFIX` by using `set(CMAKE_DEBUG_POSTFIX _d)` in SofaFramework's CMakeLists and handling executables with `set_target_properties(${PROJECT_NAME} PROPERTIES DEBUG_POSTFIX ${CMAKE_DEBUG_POSTFIX})`. Good to know!
